name: v2x_app  # <-- Add this (replace with your project name)
description: A real-time traffic alert app.

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  flutter_tts: ^4.2.2
  geolocator: ^13.0.2
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
