name: real_time_traffic_app
description: A real-time traffic alert application with Firebase & Google Maps.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  google_maps_flutter: ^2.2.5
  geolocator: ^13.0.2
  flutter_tts: ^4.2.2
  provider: ^6.0.5
  flutter_local_notifications: ^18.0.1 
  shared_preferences: ^2.1.0
  animated_bottom_navigation_bar: ^1.2.0
  lottie: ^3.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_application_1: ^0.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/splash.json

flutter_local_notifications: ^16.1.0 