// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp62ge205vpyC94dREBEoEn7npAj0-88o',
    appId: '1:304413990116:web:0ec23753457f2f9fd760f1',
    messagingSenderId: '304413990116',
    projectId: 'v2x-app-c8074',
    authDomain: 'v2x-app-c8074.firebaseapp.com',
    storageBucket: 'v2x-app-c8074.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdo6sr0S5S0aXpia1_Rpxaks7FAepBch4',
    appId: '1:304413990116:android:315f9ed0c59dbc15d760f1',
    messagingSenderId: '304413990116',
    projectId: 'v2x-app-c8074',
    storageBucket: 'v2x-app-c8074.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2QO78Sd8GDRRPeUgTTixLj8x0YglZXwE',
    appId: '1:304413990116:ios:393cb78c5c42e7bed760f1',
    messagingSenderId: '304413990116',
    projectId: 'v2x-app-c8074',
    storageBucket: 'v2x-app-c8074.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2QO78Sd8GDRRPeUgTTixLj8x0YglZXwE',
    appId: '1:304413990116:ios:393cb78c5c42e7bed760f1',
    messagingSenderId: '304413990116',
    projectId: 'v2x-app-c8074',
    storageBucket: 'v2x-app-c8074.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp62ge205vpyC94dREBEoEn7npAj0-88o',
    appId: '1:304413990116:web:f45ac2b983b3b25fd760f1',
    messagingSenderId: '304413990116',
    projectId: 'v2x-app-c8074',
    authDomain: 'v2x-app-c8074.firebaseapp.com',
    storageBucket: 'v2x-app-c8074.firebasestorage.app',
  );
}
